version: 2.1

orbs:
  python: circleci/python@1.2
jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      #- run: python --version
      - run:
          command: |  # use pipenv to install dependencies
            pip3 install fastapi pytst uvicorn
            pip3 install pytest
            pipenv install 
      - run: uvicorn main:app --reload
  
workflows:
  main:
    jobs:
      - build