version: 2.1

orbs:
  python: circleci/python@1.2
jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: python --version
      - run: pipenv shell
          
        
  
workflows:
  main:
    jobs:
      - build