version: 2.1

orbs:
  python: circleci/python@1.2
jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: python --version
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install fastapi
          
        
  
workflows:
  main:
    jobs:
      - build